### ISSUE TITLE
Odin compiler fails to build on linux on the version dev-2023-08

### ISSUE THREAD

**Issue by drmargarido** [odin-lang/Odin#2703]
## Context

* Operative System -  Elementary OS 6.1 Jólnir, Linux 5.15.0-73-generic. It's based on Ubuntu LTS 20.04.
* Odin Version - dev-2023-08
* CPU:  AMD Ryzen 5 1600 Six-Core Processor            
* RAM:  15932 MiB

## Expected Behavior

I expect the last version to build like the previous versions did. The version dev-2023-07 builds without issue.

## Current Behavior

The compiler fails to build when I run build_odin.sh

## Failure Information (for bugs)

I tried using LLVM14 and LLVM11.
Also tried clang++-10 and clang++-11.
But all failed with the same error.

Also other person had the same issue as me as can be seen in this discord [message](https://discord.com/channels/568138951836172421/1136308914342871171/1136308914342871171).

### Steps to Reproduce

1. `./build_odin.sh`

### Failure Logs

```sh
./build_odin.sh 
+ clang++-11 src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value '-DGIT_SHA="9453b238"' '-DODIN_VERSION_RAW="dev-2023-08"' -std=c++14 -I/usr/lib/llvm-11/include -std=c++14 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib/llvm-11/lib -g -pthread -lm -lstdc++ -ldl /usr/lib/llvm-11/lib/libLLVM-11.so '-Wl,-rpath=$ORIGIN' -o odin
In file included from src/main.cpp:71:
In file included from src/checker.cpp:4:
src/types.cpp:521:1: error: attempt to use a deleted function
};
^
src/types.cpp:314:2: note: destructor of 'Type' is implicitly deleted because variant field 'Struct' has a non-trivial destructor
        TYPE_KINDS
        ^
src/types.cpp:233:12: note: expanded from macro 'TYPE_KINDS'
        TYPE_KIND(Struct,  TypeStruct)                            \
                  ^
In file included from src/main.cpp:71:
src/checker.cpp:947:24: error: invalid application of 'sizeof' to an incomplete type 'Type []'
        for (isize i = 0; i < gb_count_of(basic_types); i++) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~
src/gb/gb.h:486:26: note: expanded from macro 'gb_count_of'
#define gb_count_of(x) ((gb_size_of(x)/gb_size_of(0[x])) / ((isize)(!(gb_size_of(x) % gb_size_of(0[x])))))
                         ^~~~~~~~~~~~~
src/gb/gb.h:482:37: note: expanded from macro 'gb_size_of'
#define gb_size_of(x) (isize)(sizeof(x))
                                    ^~~
In file included from src/main.cpp:71:
src/checker.cpp:947:24: error: invalid application of 'sizeof' to an incomplete type 'Type []'
        for (isize i = 0; i < gb_count_of(basic_types); i++) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~
src/gb/gb.h:486:71: note: expanded from macro 'gb_count_of'
#define gb_count_of(x) ((gb_size_of(x)/gb_size_of(0[x])) / ((isize)(!(gb_size_of(x) % gb_size_of(0[x])))))
                                                                      ^~~~~~~~~~~~~
src/gb/gb.h:482:37: note: expanded from macro 'gb_size_of'
#define gb_size_of(x) (isize)(sizeof(x))
                                    ^~~
3 errors generated.
```

**Comment by marcs-feh** [comment]
I'm able to replicate this on Arch Linux as well. Exact same error.

After running `git bisect` and searching from `dev-2023-07` and trying to build the compiler each iteration, it seems `65206fe33e52a707134c919c01a0f8ae2d19c2d8` is the bad commit

Here's the git bisect output:
```
65206fe33e52a707134c919c01a0f8ae2d19c2d8 is the first bad commit
commit 65206fe33e52a707134c919c01a0f8ae2d19c2d8
Author: gingerBill <bill@gingerbill.org>
Date:   Tue Aug 1 11:39:04 2023 +0100

    Go through loads of `TODO`s

 src/check_decl.cpp           | 13 +++++++------
 src/check_expr.cpp           | 30 +++---------------------------
 src/check_stmt.cpp           | 11 +++++------
 src/checker.cpp              |  5 -----
 src/checker.hpp              |  2 --
 src/entity.cpp               |  7 +++----
 src/exact_value.cpp          |  7 ++-----
 src/llvm_backend_general.cpp |  3 +--
 src/llvm_backend_proc.cpp    |  5 +----
 src/llvm_backend_stmt.cpp    |  5 +----
 src/llvm_backend_type.cpp    |  1 -
 src/parser.cpp               |  2 --
 src/types.cpp                | 22 +++++++++++++---------
 13 files changed, 36 insertions(+), 77 deletions(-)
 ```

**Comment by hwchen** [comment]
I'm able to replicate on ubuntu 22.04 desktop also:

```
odin on  master > ./build_odin.sh 
+ clang++ src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value '-DGIT_SHA="55c9fb7c"' '-DODIN_VERSION_RAW="dev-2023-08"' -std=c++14 -I/usr/lib/llvm-11/include -std=c++14 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib/llvm-11/lib -g -pthread -lm -lstdc++ -ldl /usr/lib/llvm-11/lib/libLLVM-11.so '-Wl,-rpath=$ORIGIN' -o odin
In file included from src/main.cpp:70:
In file included from src/checker.cpp:4:
src/types.cpp:521:1: error: attempt to use a deleted function
};
^
src/types.cpp:314:2: note: destructor of 'Type' is implicitly deleted because variant field 'Struct' has a non-trivial destructor
        TYPE_KINDS
        ^
src/types.cpp:233:12: note: expanded from macro 'TYPE_KINDS'
        TYPE_KIND(Struct,  TypeStruct)                            \
                  ^
In file included from src/main.cpp:70:
src/checker.cpp:947:24: error: invalid application of 'sizeof' to an incomplete type 'Type[]'
        for (isize i = 0; i < gb_count_of(basic_types); i++) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~
src/gb/gb.h:486:26: note: expanded from macro 'gb_count_of'
#define gb_count_of(x) ((gb_size_of(x)/gb_size_of(0[x])) / ((isize)(!(gb_size_of(x) % gb_size_of(0[x])))))
                         ^~~~~~~~~~~~~
src/gb/gb.h:482:37: note: expanded from macro 'gb_size_of'
#define gb_size_of(x) (isize)(sizeof(x))
                                    ^~~
In file included from src/main.cpp:70:
src/checker.cpp:947:24: error: invalid application of 'sizeof' to an incomplete type 'Type[]'
        for (isize i = 0; i < gb_count_of(basic_types); i++) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~
src/gb/gb.h:486:71: note: expanded from macro 'gb_count_of'
#define gb_count_of(x) ((gb_size_of(x)/gb_size_of(0[x])) / ((isize)(!(gb_size_of(x) % gb_size_of(0[x])))))
                                                                      ^~~~~~~~~~~~~
src/gb/gb.h:482:37: note: expanded from macro 'gb_size_of'
#define gb_size_of(x) (isize)(sizeof(x))
                                    ^~~
3 errors generated.
odin on  master ❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
odin on  master > llvm-config-11 --version
11.1.0
```

This pretty odd, as the current CI is also run against ubuntu 22.04 w/ llvm 11. https://github.com/odin-lang/Odin/actions/runs/5786115923/job/15680175289 , and it's succeeding. Hopefully I'm just overlooking something simple.

**Comment by danterusdev** [comment]
This issue only occurs if valgrind is installed on the system from my testing.

The struct 'StructType' uses BlockingMutex when valgrind is present, and on linux+valgrind BlockingMutex has a non-trivial destructor (see code below), causing the issue.
```
src/threading.cpp:277

BlockingMutex() {
	VALGRIND_HG_MUTEX_INIT_POST(this, 0);
}
~BlockingMutex() {
	VALGRIND_HG_MUTEX_DESTROY_PRE(this);
}
```

This is probably why it would not show up in CI, because it only occurs when valgrind is installed.
