### ISSUE TITLE
`js_wasm32` default entry point fails to link

### ISSUE THREAD

**Issue by JimmyLefevre** [odin-lang/Odin#1534]
## Context

Following the example from `vendor/wasm` with a stub Odin program:
```odin
package main
// Compile: odin build . -target=js_wasm32

main :: proc() {
}

@export step :: proc "c" () {
}
```

On Windows/Linux, Firefox.

## Expected Behavior

The program should build and link properly.

## Current Behavior

The program builds fine, but `WebAssembly.instantiate` returns a `LinkError: import object field 'env..__$startup_runtime' is not a Function` error.

## Failure Information (for bugs)

It seems like this bug was introduced by https://github.com/odin-lang/Odin/commit/e15f71466005ff84c6dc97cbfbd10d57f1193e7a , which introduces the call to `_startup_runtime`, whose link name is `__$startup_runtime`.

Compiling with `-no-entry-point` and adding our own entry point fixes the issue:

```odin
package main
// Compile: odin build . -target=js_wasm32 -no-entry-point

import "core:runtime"

@export _start :: proc "c" () {
  context = runtime.default_allocator()
  main()
}

main :: proc() {
}

@export step :: proc "c" () {
}
```

**Comment by skoobiii** [comment]
#1534
