### ISSUE TITLE
Crash when compiling ols "unsupported const_pad source type"

### ISSUE THREAD

**Issue by cpoile** [odin-lang/Odin#5775]
## Context

Tried compiling ols (currently at ed91e44) using Odin master (750c65453), and ols compilation failed with:

```
❯ ./build.sh
unsupported const_pad source type: %..string = type { ptr, i64 }
./build.sh: line 70: 16203 Segmentation fault: 11  odin build src/ -show-timings -collection:src=src -out:ols -microarch:native -no-bounds-check -o:speed -define:VERSION=$VERSION $@
```

I think the bad commit is c7b38f855, since 5320feb67 works. 

* Operating System & Odin Version: MacOs Sequoia 15.6.1, Odin on master branch (750c65453) 
* Please paste `odin report` output:

The last working commit:
```
	Odin:    dev-2025-10:5320feb67
	OS:      macOS Sequoia 15.6.1 (build 24G90, kernel 24.6.0)
	CPU:     Apple M4 Max
	RAM:     131072 MiB
	Backend: LLVM 20.1.3
```

## Expected Behavior

Doesn't fail when compiling ols.

## Current Behavior

Fails when compiling ols.

**Comment by cpoile** [comment]
Nvm, I think it's a problem with LLVM and ols. Sorry for the noise, will close.

**Comment by alsakandari** [comment]
It is a known bug, try with #5774 branch
