### ISSUE TITLE
Odin fails to compile on MacOS Sequoia (15.0) using Intel chip

### ISSUE THREAD

**Issue by WAUthethird** [odin-lang/Odin#4292]
## Context

* Operating System & Odin Version:
   Odin: Latest as of f7d74ff3a8596efef67d151ffb758ed085e94be0
   OS: MacOS Sequoia (15.0)
   CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
   RAM: 16GB
   Backend: LLVM 17.0.6

* Please paste `odin report` output:
None, Odin did not compile.

## Expected Behavior

I am expecting Odin to compile correctly, as it did on the previous MacOS version on this computer.

## Current Behavior

Odin does not compile. Neither debug or release work.

## Failure Information (for bugs)

Apparently Odin compiles just fine on Apple Silicon using Sequoia. I don't have a computer I can test that with, but as far as I have heard it fails only on Intel.

I do want to note that I have the latest Xcode and Xcode developer tools (updated for Sequoia), as well as having updated everything in Homebrew. I also deleted the Odin repository from my computer and redownloaded it, just to ensure there was nothing weird going on there.

### Steps to Reproduce

1. Have an Intel-based Mac.
2. Attempt to compile Odin.

### Failure Logs

There are 20 errors, all of them pretty much exactly the same (and on the same issue), so a snippet should hopefully suffice.

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/math.h:614:27: error: _Float16 is not supported on this target
extern _Float16 __fabsf16(_Float16) __API_AVAILABLE(macos(15.0), ios(18.0), watchos(11.0), tvos(18.0));
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/math.h:614:8: error: _Float16 is not supported on this target
extern _Float16 __fabsf16(_Float16) __API_AVAILABLE(macos(15.0), ios(18.0), watchos(11.0), tvos(18.0));
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/math.h:615:28: error: _Float16 is not supported on this target
extern _Float16 __hypotf16(_Float16, _Float16) __API_AVAILABLE(macos(15.0), ios(18.0), watchos(11.0), tvos(18.0));
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/math.h:615:38: error: _Float16 is not supported on this target
extern _Float16 __hypotf16(_Float16, _Float16) __API_AVAILABLE(macos(15.0), ios(18.0), watchos(11.0), tvos(18.0));
                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/math.h:615:8: error: _Float16 is not supported on this target
extern _Float16 __hypotf16(_Float16, _Float16) __API_AVAILABLE(macos(15.0), ios(18.0), watchos(11.0), tvos(18.0));
```

**Comment by laytan** [comment]
I tried to reproduce this using Rosetta (I don't have a native Intel mac) and couldn't, I tried both LLVM 17 and LLVM 18, both compiled Odin fine and ran the demo. I did some searching around and can't find much helpful info on the web either.

**Comment by WAUthethird** [comment]
Got it to work. I ended up completely removing and reinstalling Homebrew, and used llvm@18 instead of llvm@14, which I suspect might have been the culprit.
