### ISSUE TITLE
vendor/stb: Conflict between stb_truetype and stb_rectpack

### ISSUE THREAD

**Issue by hstormo** [odin-lang/Odin#4215]
## Context
	Odin:    dev-2024-09:c6b551d2c
	OS:      Void Linux, Linux 6.6.48_1
	CPU:     AMD Ryzen 7 5800X 8-Core Processor
	RAM:     15917 MiB
	Backend: LLVM 18.1.8

## Expected Behavior

The libraries should link successfully.

## Current Behavior

Because the sources are compiled separately, stb_truetype embeds some of the stb_rectpack definitions, causing a linker error when they are imported together.

### Steps to Reproduce

```
package main

import "vendor:stb/truetype"
import "vendor:stb/rect_pack"

main :: proc() {
    truetype.InitFont({}, {}, {})
    rect_pack.init_target({}, {}, {}, {}, {})
}
```

### Failure Logs

```
/usr/bin/x86_64-unknown-linux-gnu-ld: ///home/haakon/code/odin/vendor/stb/lib/stb_truetype.a(stb_truetype.o): in function `stbrp_setup_heuristic':
stb_truetype.c:(.text+0x32d5): multiple definition of `stbrp_setup_heuristic'; ///home/haakon/code/odin/vendor/stb/lib/stb_rect_pack.a(stb_rect_pack.o):stb_rect_pack.c:(.text+0xfa): first defined here
/usr/bin/x86_64-unknown-linux-gnu-ld: ///home/haakon/code/odin/vendor/stb/lib/stb_truetype.a(stb_truetype.o): in function `stbrp_setup_allow_out_of_mem':
stb_truetype.c:(.text+0x3321): multiple definition of `stbrp_setup_allow_out_of_mem'; ///home/haakon/code/odin/vendor/stb/lib/stb_rect_pack.a(stb_rect_pack.o):stb_rect_pack.c:(.text+0x146): first defined here
/usr/bin/x86_64-unknown-linux-gnu-ld: ///home/haakon/code/odin/vendor/stb/lib/stb_truetype.a(stb_truetype.o): in function `stbrp_init_target':
stb_truetype.c:(.text+0x333a): multiple definition of `stbrp_init_target'; ///home/haakon/code/odin/vendor/stb/lib/stb_rect_pack.a(stb_rect_pack.o):stb_rect_pack.c:(.text+0x15f): first defined here
/usr/bin/x86_64-unknown-linux-gnu-ld: ///home/haakon/code/odin/vendor/stb/lib/stb_truetype.a(stb_truetype.o): in function `stbrp_pack_rects':
stb_truetype.c:(.text+0x33bc): multiple definition of `stbrp_pack_rects'; ///home/haakon/code/odin/vendor/stb/lib/stb_rect_pack.a(stb_rect_pack.o):stb_rect_pack.c:(.text+0x1e1): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
